server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rule_pile?characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root

mybatis:
  configuration:
    map-underscore-to-camel-case: true
